modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL=""

[[mixins]]
config="worldmodifier.mixins.json"

[[mods]]
modId="worldmodifier"
version="1.0.0"
displayName="World Modifier"
description='''
A mod that allows you to modify world generation settings.
Control which biomes generate, adjust sea level, and customize your world.
'''
authors="WorldModifier"
displayURL=""

[[dependencies.worldmodifier]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.worldmodifier]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
